version: '2'

services:
  wordpress:
    image: wordpress:php7.3
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: root
    volumes:
      - ..:/var/www/html/wp-content/plugins/geo-mashup
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
